### ISSUE TITLE
Security Airlocks on the bead don't look right when closed

### ISSUE THREAD

**Issue by VladinXXV** [voidcrew/Voidcrew-LRP#12]
Issue reported from  Round ID: 90 (Voidcrew-LRP)

Reporting client version: 514.1571

![image](https://user-images.githubusercontent.com/44104681/150276660-d4de3a60-79eb-48bd-9da1-e5b9534b3632.png)

**Comment by VladinXXV** [comment]
This resolved itself later on. May have been clientside, may just be hard to reproduce. No clue.

**Comment by Striketester** [comment]
that isnt a mapping failure, its a common byond bug that happens.
