### ISSUE TITLE
Scrapper (Not B) Ship broken.

### ISSUE THREAD

**Issue by shelteredfreak** [voidcrew/Voidcrew-LRP#120]
Issue reported from  Round ID: 209 (Voidcrew-LRP)

Reporting client version: 514.1569

![scrapper broke](https://user-images.githubusercontent.com/81834422/152615189-dd9e64ca-4323-4bcb-88ae-f1d64598b9a5.PNG)
I get to see this lovely image, then I wait.... and I wait.... then I wait more.... soon coming to realize that I dont think the ship is coming any time soon.

I looked on the shiptest wiki and the shiptest maps and the Scrapper can be found nowhere. Does it just not exist? If so, why is it available for purchase then?

I feel like it should either be removed or fixxed, whatever may be wrong with it.

**Comment by SuperNovaa41** [comment]
Fixed
