### ISSUE TITLE
Detroit: SS13

### ISSUE THREAD

**Issue by shelteredfreak** [voidcrew/Voidcrew-LRP#132]
Issue reported from  Round ID: 220 (Voidcrew-LRP)

Reporting client version: 514.1569

I was trying to sell some Frost Diamonds and Draconic Amber with a cargo hold pad.

Then suddenly while I was standing on it, a FUCK TON of my stuff got ripped off me. And apparently sold.

I REALLY feel like this shouldnt be intentional. It should only sell items that are laying down. It shouldnt sell the contents off a PERSON.

Motherfuckers sold my stuff right off my back, cant have shit in Voidcrew.

**Comment by theta006** [comment]
thats not a bug stand on the bad and trigger the cost scan it will show everything it will take from you. you are lucky its not the pirate pad that will sell your body
