### ISSUE TITLE
Mining Scanners Are Kill

### ISSUE THREAD

**Issue by VladinXXV** [voidcrew/Voidcrew-LRP#206]
Issue reported from  Round ID: 271 (Voidcrew-LRP)

Reporting client version: 514.1571

Automatic mining scanners and advanced automatic mining scanners are not available in the mining rewards vendor.

**Comment by Sbmhawk** [comment]
I think #191 did this when they removed dual and advanced dual, which were the upgrades to automatic, I do not think automatic was ever in there.

**Comment by VladinXXV** [comment]
Automatic and advanced automatic exist in the code still but were replaced in the vendor by their deepcore versions. Now that the deepcore versions are gone, the vendors just don't offer any scanners at all. It's easy enough to fix but I'm lazy.
