### ISSUE TITLE
Survivor Suit Hood Missing Icon

### ISSUE THREAD

**Issue by VladinXXV** [voidcrew/Voidcrew-LRP#207]
Issue reported from  Round ID: 271 (Voidcrew-LRP)

Reporting client version: 514.1571

The survivor suit (found off survivor fauna on sand planet or on the shetland-class) has no item sprite for the hood. When the hood is up, the slot in your inventory for headgear will SEEM empty.
![image](https://user-images.githubusercontent.com/44104681/153802027-10a6c92b-c6ed-40c6-ace3-6b3cf198a2c7.png)

**Comment by SweptWasTaken** [comment]
I'll look into this one.
