### ISSUE TITLE
AI camera Error "ERROR: Eyeobj not found. Creating new eye... " after ship changes z-level

### ISSUE THREAD

**Issue by Nexofas** [voidcrew/Voidcrew-LRP#215]
Issue reported from  Round ID: 276 (Voidcrew-LRP)

Reporting client version: 514.1578

Long ago AI cameras lived in peace.Until the z-level nation attacked and when AI cameras were needed the most they vanished.
They also mysteriously appeared later just to go full black when another z-level transition was striked.

**Comment by SuperNovaa41** [comment]
Duplicate of https://github.com/Jackriip/Voidcrew-LRP/issues/83
