### ISSUE TITLE
[BUG] Metacoins do not pay out every ten minutes

### ISSUE THREAD

**Issue by Jackriip** [voidcrew/Voidcrew-LRP#23]
https://github.com/shiptest-ss13/Shiptest/issues/670

Metacoins do not pay out every ten minutes like they are supposed to. They only pay out at the end of the round.

**Comment by dwasint** [comment]
I cannot find anything that references the process_ten_minute_living() aside from job xp which doesn't appear to do anything, that may be the reason metacoins are not generated.

**Comment by SuperNovaa41** [comment]
it definitely is, i plan to add something to track what that is doing, so i can see why its not updating. It's nearly impossible to test on local because it requires a database and players

**Comment by dwasint** [comment]
That would explain it, i tried looking around at other servers to see if they use something similar but wasn't able to find anything aside from other downstreams of shiptest.
