### ISSUE TITLE
Gasses refuse to sell

### ISSUE THREAD

**Issue by bsolomon9** [voidcrew/Voidcrew-LRP#250]
## Round ID: Private server 

When a canister is sold on a cargo hold pad, no matter the purity of the gas in the canister, the gas is not sold and only the canister is valued ignoring the gas completely

**Comment by dwasint** [comment]
Not a bug whitesands removed that feature `/*WS Begin - Cargo Rebalance?

/datum/export/large/gas_canister
	cost = 10 //Base cost of canister. You get more for nice gases inside.
	unit_name = "Gas Canister"
	export_types = list(/obj/machinery/portable_atmospherics/canister)
/datum/export/large/gas_canister/get_cost(obj/O)
	var/obj/machinery/portable_atmospherics/canister/C = O
	var/worth = 10

	worth += C.air_contents.get_moles(GAS_BZ)*4
	worth += C.air_contents.get_moles(GAS_STIMULUM)*100
	worth += C.air_contents.get_moles(GAS_HYPERNOB)*1000
	worth += C.air_contents.get_moles(GAS_MIASMA)*10
	worth += C.air_contents.get_moles(GAS_TRITIUM)*5
	worth += C.air_contents.get_moles(GAS_PLUOXIUM)*5
	worth += C.air_contents.get_moles(GAS_FREON)*5
	return worth

WS end */
`
