### ISSUE TITLE
KoS ships immune to interdiction

### ISSUE THREAD

**Issue by Addust** [voidcrew/Voidcrew-LRP#274]
Issue reported from  Round ID: 340 (Voidcrew-LRP)

Reporting client version: 514.1575

![image](https://user-images.githubusercontent.com/80979251/155625439-c2f043b5-ccac-4352-b7cb-33f33c742744.png)

**Comment by Sbmhawk** [comment]
They probably just changed thier name to kos, but didn't hit the actual kos button 

If I had to guess

**Comment by Thaums** [comment]
bit late but ye thats whats happening, if their ship is white then theyre still NEU
