### ISSUE TITLE
BD miner eye will break your fucking kneecaps (quite literally)

### ISSUE THREAD

**Issue by Addust** [voidcrew/Voidcrew-LRP#285]
Issue reported from  Round ID: 356 (Voidcrew-LRP)

Reporting client version: 514.1575

Self-explanatory, it breaks your fucking bones

**Comment by Foxtro1** [comment]
Oooh so that's why bones were breaking so easily... I thought that was because I played a kepori. Literally had two and more broken bones per fight with a tumor, while not getting damaged at all, which seemed strange at the time...
