### ISSUE TITLE
[BUG] Crusher Multiple Shrunken 

### ISSUE THREAD

**Issue by StarZero9** [voidcrew/Voidcrew-LRP#73]
Issue reported from  Round ID: 173 (Voidcrew-LRP)

Reporting client version: 514.1577

You can add multiples Shrunken skulls in the crusher, doing it shoot 1,2 seconds faster, it become really OP

![image](https://user-images.githubusercontent.com/98711473/151715365-bf6d2e02-1b5b-4209-b66e-03e0f7290ef8.png)

**Comment by StarZero9** [comment]
In that case i added two and got 1,2 seconds faster, but i think you can add more

**Comment by dwasint** [comment]
can confirm it has no limit
![image](https://user-images.githubusercontent.com/82520990/152373166-11acaecc-2ce1-488c-838b-2be7e86c3d8b.png)

**Comment by Dennok** [comment]
This fixed. Why not closed?
