### ISSUE TITLE
Xenobiology Console not-quite a softlock

### ISSUE THREAD

**Issue by VladinXXV** [voidcrew/Voidcrew-LRP#74]
Issue reported from  Round ID: 173 (Voidcrew-LRP)

Reporting client version: 514.1571

Using a xenobiology console creates a camera eye. When the ship moves, this eye is left behind. Inititally, this happened when my ship left a planet, but I was able to bring the eye back to the ship using the jump to camera button. When we landed on another planet, however, the console only shows black, and none of the buttons, including the one to exit the console, work.

![image](https://user-images.githubusercontent.com/44104681/151715769-65a9383d-7075-445a-aa1a-27b62b0eade2.png)

I think the camera eye was deleted when the ship left hyperspace, maybe? Not sure. Possibly an issue for other cameras/AIs.

Edit: I thought this was a softlock but you can actually get out on your own by laying down. Still, though.

**Comment by dwasint** [comment]
if you want to fix this in the mean time disconnect and reconnect the xeno console
